<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link rel="stylesheet" href="assets/bootstrap/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="assets/bootstrap/dist/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="css/main.css">
        <link rel="stylesheet" href="assets/DataTables/media/css/jquery.dataTables.css" type="text/css">
    </head>
    <body>
        <!-- Header -->
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p>&nbsp;</p>
                </div>
            </div>
        </div>
        <!-- end Header -->
        <!-- Nav -->
        <div class="container-fluid">
            <div class="container">
	            <div class="row">
	                <div class="col-md-12">
	                    
	                </div>
	            </div>
	        </div>
	    </div>
	    <!-- endNav -->
	    <!-- Body -->
                <?= $this->content ?>
        <!-- end Body -->
        <!-- Footer 1 -->
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <p>&nbsp;</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- end Footer 1 -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="assets/jquery/dist/jquery.min.js"><\/script>')</script>
        <script src="assets/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="assets/DataTables/media/js/jquery.dataTables.js"></script>
        <script type="text/javascript" src="js/main.js"></script>

    </body>
</html>
