<div class="container">
<div class="page-header">
    <h1>Manager Views</h1>
</div>
<div class="bg-classes">
</div>
<table class ="table table-hover" id="user" class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Login</th>
            <th>Role</th>
            <th>Actions</th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($this->users as $user): ?>
        <tr>
            <td><?= $user['id'];?></td>
            <td><?= $user['login'];?></td>
            <td><?= $user['role'];?></td>
            <td>
                <a class= "delete" href='/deleteUser?id=<?=$user['id']; ?>'>Delete</a>
                <a href='/updateUser'>Update</a>
            </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
<a href = "home" class= "btn btn-danger pull-right">Retour</a>
</div>